spring.application.name=shortlinkx

# Database Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=${PORT:8080}

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000

# Error Response
server.error.include-message=always

# Groq AI
app.groq.api-key=${GROQ_API_KEY}
app.groq.model=${GROQ_MODEL:openai/gpt-oss-20b}
app.groq.endpoint=${GROQ_ENDPOINT:https://api.groq.com/openai/v1/chat/completions}